INSERT INTO BUILD  (BUILD_ID ,BUILD_NAME ) VALUES ('1','S3');
INSERT INTO BUILD  (BUILD_ID ,BUILD_NAME ) VALUES ('2','S7');

INSERT INTO DIVISION (DIVISION_ID, DIVISION_NAME) VALUES (1, 'Kpngphop');

INSERT INTO USERS (USER_MAIL, USER_NAME, USER_PHONE, USERTYPE) VALUES ('DUGJ', 'BEN', '095382', 'STUDENT');
INSERT INTO USERS (USER_MAIL, USER_NAME, USER_PHONE, USERTYPE) VALUES ('DUGJ', 'BEN', '095382', 'STUDENT');


