CREATE TABLE BUILD (
    BUILD_ID BIGINT PRIMARY KEY,
    BUILD_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE USERS (
    USER_ID BIGINT PRIMARY KEY,
    USER_NAME VARCHAR(50) NOT NULL,
    USER_TYPE VARCHAR(50) NOT NULL,
    USER_MAIL VARCHAR(50) NOT NULL,
    USER_PHONE VARCHAR(50) NOT NULL
);
